[package]
name = "fb2sqlite"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.43"
csv = "1.4.0"
reqwest = { version = "0.13.1", features = ["blocking"] }
rusqlite = "0.38.0"
